### PR TITLE
Define blocks for easy overriding of the page rendering

### PR DESCRIPTION
**Pull request by Aeliot-Tm**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documented?   | yes
| License       | MIT

**There are added new blocks for easy overriding of the page rendering**.
It is useful then you want to add new fields on the page. 

For example, for handling of API assess tokens.

x-auth-token

#### Additionally:
- Docs moved from the `src/Resouces/doc` directory to `docs` in the repository root.
- Fixed links to them in `README.md`.
- Restored docs which was removed by chance before.

### CODE REVIEW

**Comment by Aeliot-Tm** [comment]
May be it has sense to create a set of templates for common solutions?

**Comment by Aeliot-Tm** [comment]
@mcg-web Could you check it, please

**Comment by Aeliot-Tm** [comment]
Added template [@OverblogGraphiQL/GraphiQL/auth.html.twig](../src/Resources/views/GraphiQL/auth.html.twig) providing two common authentication ways. 

How it looks like:
auth-token
There is:

1. Header used for the authorization.
2. Header value (token) for the authorization.
3. Button to load schema when the header value (token) typed.

**Comment by Aeliot-Tm** [comment]
@ruudk @mcg-web  Could you check it, please?

**Review by mcg-web — APPROVED** [review]

**Comment by mcg-web** [comment]
Thank you and sorry for the late reply!

**Pull request merged**
