### PR TITLE
Symfony 5.0 Support

### PR DESCRIPTION
**Pull request by benji07**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes/no
| Documented?   | no
| License       | MIT

Allow installation with Symfony5

### CODE REVIEW

**Comment by mcg-web** [comment]
I'm giving a hand on this so we can release a patch

**Comment by benji07** [comment]
the test are ok, but, i had to raise the minimum symfony version to 3.4 (and i have 1 job that fail because of memory

**Comment by mcg-web** [comment]
I removed dev flag to fix the memory issue

**Comment by mcg-web** [comment]
thank you @benji07 :+1:

**Pull request merged**
